### ISSUE TITLE
Plugin Configuration

### ISSUE THREAD

**Issue by juliankrispel** [nikgraf/draft-js-plugins#66]
Mention Plugin

```js
{
  mentions: List([Map({
    link: String,
    avatarUrl: String  
  })]),
  theme: {
    search: Map(),
    mention: Map(),
   },
}
```

Hashtag Plugin
```js
{
   theme: {
      hashtag: Map(),
   }
}
```

Undo Plugin
```js
{
  theme: {
    undoButton: Map(),
    redoButton: Map(),
  }
}
```

Link Plugin
```js
{
   theme: {
      link: Map(),
   }
}
```

stickerPlugin
```js
{
   theme: {
     sticker: Map(),
     stickerSelect: Map(),
   }
}
```

emojiPlugin

```js
{
   emojis: List([Map(
     url: String,
     name: String,
     key: String,
     unicodeCharacter: String, // (replaced with image, should only show image if it is in the list of emojis)
   )]),
   theme: {
     emoji: Map(),
     emojiSelect: Map(),
   }
}
```

**Comment by nikgraf** [comment]
@juliankrispel I just checked out thoughts here again. How would the config for the mention plugin look like with a callback function that returns a promise to fetch data from a server?

Should `mentions` be either a List or function or rather have two props? Maybe something else?

**Comment by juliankrispel** [comment]
@nikgraf I guess it could be optional: `list` or a `function` returning a list, or a `promise` which returns a list.

**Comment by nikgraf** [comment]
sounds good to me :+1:

**Comment by nikgraf** [comment]
done :smile:
